package edu.ub.prog2.VinagreJorgeOteroJoel.vista;

import edu.ub.prog2.VinagreJorgeOteroJoel.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FrmAfegirFitxerMultimedia extends javax.swing.JDialog {
    Controlador controlador;
    JFrame comingFrame;

    /**
     * Creates new form AplicacioUB4
     * @param comingFrame Our main JFrame object
     * @param controlador Our controler object
     */
    public FrmAfegirFitxerMultimedia(JFrame comingFrame, Controlador controlador) {
        /* Attribute defining */
        this.comingFrame = comingFrame;
        this.controlador = controlador;
        
        /* Components initialization */
        initComponents();
        this.setResizable(false);
        searchImage.setVisible(false);
        etCamiImatge.setVisible(false);
        textCamiImatge.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        etCami = new javax.swing.JLabel();
        textCami = new javax.swing.JTextField();
        searchFile = new javax.swing.JButton();
        etCamiImatge = new javax.swing.JLabel();
        searchImage = new javax.swing.JButton();
        textCamiImatge = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        etNom = new javax.swing.JLabel();
        selectType = new javax.swing.JComboBox<>();
        btnAcceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        etCami.setText("Camí Arxiu:");

        textCami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCamiActionPerformed(evt);
            }
        });

        searchFile.setText("Buscar");
        searchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFileActionPerformed(evt);
            }
        });

        etCamiImatge.setText("Camí Imatge:");

        searchImage.setText("Buscar");
        searchImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchImageActionPerformed(evt);
            }
        });

        textCamiImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCamiImatgeActionPerformed(evt);
            }
        });

        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });

        etNom.setText("Nom:");

        selectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Video", "Audio" }));
        selectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTypeActionPerformed(evt);
            }
        });

        btnAcceptar.setText("Acceptar");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etCami)
                    .addComponent(etCamiImatge)
                    .addComponent(etNom))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(textCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(searchImage))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(textCami, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(searchFile)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etCami)
                    .addComponent(searchFile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCamiImatge)
                    .addComponent(searchImage)
                    .addComponent(textCamiImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNom))
                .addGap(18, 18, 18)
                .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // unused
    private void textCamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCamiActionPerformed
    }//GEN-LAST:event_textCamiActionPerformed

    /**
     * On video/audio type selected,  we show the image path or not
     * @param evt ActionEvent
     */
    private void selectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTypeActionPerformed
        if (selectType.getSelectedIndex() == 1) {
            searchImage.setVisible(true);
            etCamiImatge.setVisible(true);
            textCamiImatge.setVisible(true);
        } else {
            searchImage.setVisible(false);
            etCamiImatge.setVisible(false);
            textCamiImatge.setVisible(false);
        }
    }//GEN-LAST:event_selectTypeActionPerformed

    /**
     * Method to get the selected file and save the path and name (desc)
     * @param evt ActionEvent
     */
    private void searchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFileActionPerformed
        File fitxer;
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter;
        if (selectType.getSelectedIndex() == 0) {
            filter = new FileNameExtensionFilter("Arxius de video",
                    "mp4", "asf", "wmv", "avi", "flv", "mov", "mpeg", "mpg");
        } else {
            filter = new FileNameExtensionFilter("Arxius d'audio",
                    "mp3", "wav", "ogg", "3gp", "m4a", "wma");
        }
        jf.setAcceptAllFileFilterUsed(false);
        jf.addChoosableFileFilter(filter);
        
        int sel = jf.showOpenDialog(this);
        
        if (sel == JFileChooser.APPROVE_OPTION) {
            fitxer = jf.getSelectedFile();
            textCami.setText(fitxer.getAbsolutePath());
            textNom.setText(fitxer.getName().replaceFirst("[.][^.]+$", ""));
        }
    }//GEN-LAST:event_searchFileActionPerformed

    // unused
    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
    }//GEN-LAST:event_textNomActionPerformed

    /**
     * Method to get the path of the selected image
     * @param evt ActionEvent
     */
    private void searchImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchImageActionPerformed
        File fitxer;
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arxius d'imatge",
                    "png", "jpg", "jpeg", "gif", "svg");
        jf.setAcceptAllFileFilterUsed(false);
        jf.addChoosableFileFilter(filter);
        
        int sel = jf.showOpenDialog(this);
        
        if (sel == JFileChooser.APPROVE_OPTION) {
            fitxer = jf.getSelectedFile();
            textCamiImatge.setText(fitxer.getAbsolutePath());
        }
    }//GEN-LAST:event_searchImageActionPerformed

    /**
     * Add the file to the library and show again the main jframe
     * @param evt ActionEvent
     */
    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        boolean exception_caught = false;
        String codec;
        if (selectType.getSelectedIndex() == 0) {
            if (textNom.getText().indexOf('.') > -1) codec = textCami.getText().substring(textCami.getText().lastIndexOf("."));
            else codec = "Sense codec";
            try {
                controlador.afegirVideo(textCami.getText(), textNom.getText(), codec , 0, 0, 0, 60);
            } catch (AplicacioException e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Inane error", JOptionPane.ERROR_MESSAGE);
                exception_caught = true;
            }
        } else {
            if (textNom.getText().indexOf('.') > -1) codec = textCami.getText().substring(textCami.getText().lastIndexOf("."));
            else codec = "Sense codec";
            try {
                controlador.afegirAudio(textCami.getText(), textCamiImatge.getText(), textNom.getText(), codec, 0, 0);
            } catch (AplicacioException e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Inane error", JOptionPane.ERROR_MESSAGE);
                exception_caught = true;
            }
        }
        
        if (!exception_caught) {
            JOptionPane.showMessageDialog(new JFrame(), "El fitxe s'ha afegit a la llibreria!", "Informació", JOptionPane.INFORMATION_MESSAGE);
        }
        this.setVisible(false);
        AplicacioUB4Remastered appub = (AplicacioUB4Remastered) comingFrame;
        appub.refreshTableBiblioteca();
        comingFrame.setVisible(true);
    }//GEN-LAST:event_btnAcceptarActionPerformed

    // unused
    private void textCamiImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCamiImatgeActionPerformed
    }//GEN-LAST:event_textCamiImatgeActionPerformed

    /**
     * Cancel the adding of a new file and show again the main jframe
     * @param evt ActionEvent
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        comingFrame.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel etCami;
    private javax.swing.JLabel etCamiImatge;
    private javax.swing.JLabel etNom;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchFile;
    private javax.swing.JButton searchImage;
    private javax.swing.JComboBox<String> selectType;
    private javax.swing.JTextField textCami;
    private javax.swing.JTextField textCamiImatge;
    private javax.swing.JTextField textNom;
    // End of variables declaration//GEN-END:variables
}
